name: Hello Pipeline #имя workflow
#on: [push] #работает при пуше
on: workflow_dispatch
jobs:
  say-hello: #имя джоба
    runs-on: ubuntu-latest #на чем будет работать
    steps:
      #можно указать имя через -name
      - uses: actions/checkout@v4
      - run: bash hello.sh
  show-files:
    runs-on: ubuntu-latest
    steps:
      - name: Commands
        uses: actions/checkout@v4
      - run: pwd
      - run:  |
          node -v
          npm -v